### ISSUE TITLE
File Download Servlet

### ISSUE THREAD

**Issue by dinasadir** [mjimenez98/message-board#16]
**Requirements**

Return file content

Params:

- Post id
- Attachment id

Error:

- Return generic error message
- Redirect user to error page (jsp exception)

- Use appropriate content-type in case of success or error (jpeg vs. text vs. gif…)
- Use appropriate content-disposition header to specify a proper filename
- Make sure the client does not cache the data
- Never access the file directly. Call business layer.
- Receive data from business layer in binary format (byte array)
- Optional: receive an output stream by which the method reads the file and writes the content into the given output stream

**Comment by mjimenez98** [comment]
Resource: https://www.codejava.net/java-ee/servlet/java-servlet-to-download-file-from-database
